# controller_node.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3
"""
Implementation of the Guidance and Control Layer (Layer 3) of the HybrautNav 
Navigation Stack.

This layer integrates the finite-time high-level guidance controller and 
produces reference commands—desired yaw rate and desired velocity—that will 
be tracked by downstream low-level controllers (e.g., PID, differential-drive, 
MPC). It acts as the closure of the HybrautNav stack for fast control loops, 
bridging the tactical continuous dynamics and the physical control execution.

Responsibilities:
- Integrates the high-level guidance controller into real-time control loops
- Enforces safety limits and parameter constraints
- Provides hardware interfacing pathways (rudder, thrusters, actuators)
- Allows the L2 Tactical Layer to remain physics-agnostic by handling 
  vessel-specific control considerations here

NOTE:
This version of the controller assumes a constant forward velocity and relies
on the continuous dynamics from the hybraut_tactical_layer to supply only a
desired heading. Future versions may support richer dynamic references.

Interface: no manual activation step. The control loop timer always runs;
whether it commands real motion is driven entirely by whether
`/hybraut_nav/continous_dynamics` is actively being published to (see
`_is_tactical_active()`) - that's the same "is a leg currently executing"
signal tactical_node's own action-driven publish timer expresses (it only
publishes continous_dynamics while a leg is running). While stale (no leg
running, or tactical_node isn't up), an explicit zero-velocity command is
published instead of the last real command, so the robot doesn't keep
coasting once the tactical layer is done.
"""

import math
from typing import Optional

from rclpy.callback_groups import ReentrantCallbackGroup
import os

import rclpy
from rclpy.node import Node
from rclpy.time import Time
from rclpy.duration import Duration
from rclpy.qos import qos_profile_system_default
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.subscription import Subscription
from rclpy.publisher import Publisher
from rcl_interfaces.msg import ParameterDescriptor
from rclpy.qos import QoSProfile, HistoryPolicy, ReliabilityPolicy, DurabilityPolicy

from geometry_msgs.msg import TwistStamped, TransformStamped, Twist
from nav_msgs.msg import Odometry

from hybraut_nav.qos import world_state_qos

from std_msgs.msg import Float64MultiArray

from hybraut_nav_utils import quaternion_to_heading

from .controller import ControllerType, Controller

from rcl_interfaces.msg import ParameterType

DEFAULT_CONTROLLER_FREQUENCY: float = 100.0  # Hz
DEFAULT_CRUISE_SPEED: float = 7.2 # m/s = 15 knots
DEFAULT_YAW_RATE_LIMIT: float = 0.5 # yaw rate
DEFAULT_CONTINUOUS_DYNAMICS_TIMEOUT: float = 0.5  # s

import numpy as np


class ImmediateNode(Node):
    """
    ImmediateNode is a core component of the HybrautNav Navigation Stack,
    integrating a heading-guidance controller into the
    Planning–Behaviour–Guidance architecture.

    This node computes high-level guidance commands—specifically desired
    yaw rate and desired velocity—based on the continuous dynamics provided
    by the L2 Tactical Layer’s Hybrid Automaton and the current state of the
    agent vehicle. In this version, the controller assumes a constant forward
    velocity and uses the desired heading from the tactical layer as its
    primary reference.

    The underlying controller is pluggable via the `controller_type` ROS
    parameter (see `ControllerType`) - defaults to a PID controller for
    now, since the intended finite-time guidance controller
    (`finite_time_control`) isn't published/ready yet. It produces
    reference commands that downstream low-level controllers can track,
    incorporating the vessel’s physical parameters as needed.

    This node also manages dynamic reconfiguration of controller parameters
    and supports runtime switching of control modes—whether triggered manually
    by a human operator or automatically via updates from continuous-dynamics
    messages generated by the tactical layer.
    """

    # internal state
    ctrl: Optional[Controller] = None

    desired_heading: float = 0.0
    desired_yaw_rate: float = 0.0

    # Subscriptions
    odom_sub: Subscription = None
    # Publishers
    cmd_vel_pub: Publisher = None

    def __init__(self):
        super().__init__('immediate_node', namespace='hybraut_nav')

        # last time a continous_dynamics message arrived - None until the
        # first one ever does. Drives _is_tactical_active(); see module
        # docstring for why liveness of that topic (rather than a manual
        # activation step) is the right signal here.
        self._last_continous_dynamics_time: Optional[Time] = None
        # edge-detect flag for control_loop's active/inactive transition
        # logging + the controller reset on resume - not itself used to
        # gate publishing (that's a direct _is_tactical_active() check every
        # tick, see control_loop).
        self._was_tactical_active: bool = False

        self.__init_parameters__()
        self.__init_subscriptions__()
        self.__init_publishers__()
        self.__init_timers__()
        self.__init_controller__()

    def __init_parameters__(self):
        self.declare_parameter(
            'controller_frequency',
            DEFAULT_CONTROLLER_FREQUENCY,
            ParameterDescriptor(
                description='Frequency (Hz) at which to run the controller loop. '
                            f'(default: {DEFAULT_CONTROLLER_FREQUENCY} Hz)',
                type=ParameterType.PARAMETER_DOUBLE
            )
        )
        self.declare_parameter(
            'controller_type',
            ControllerType.PID_CONTROLLER.value,
            ParameterDescriptor(
                description='Which guidance controller to run - see ControllerType '
                            f'(default: "{ControllerType.PID_CONTROLLER.value}")',
                type=ParameterType.PARAMETER_STRING
            )
        )
        self.declare_parameter(
            'desired_velocity',
            DEFAULT_CRUISE_SPEED,
            ParameterDescriptor(
                description='Velocity (m/s) in which the controller will' \
                    f'operate a cruise speed, this version of hybraut_nav_controller' \
                    f'outputs a constant cruise speed for `cmd_vel` based on this' \
                    f'(default: {DEFAULT_CRUISE_SPEED})',
                type=ParameterType.PARAMETER_DOUBLE
            ),
        )
        self.declare_parameter(
            'yaw_rate_limit',
            DEFAULT_YAW_RATE_LIMIT,
            ParameterDescriptor(
                description=(
                    'Yaw rate limit defines the constraints of yaw rate for the '
                    f'guidance controller (default: {DEFAULT_YAW_RATE_LIMIT})'
                ),
                type=ParameterType.PARAMETER_DOUBLE
            )
        )
        self.declare_parameter(
            'continuous_dynamics_timeout',
            DEFAULT_CONTINUOUS_DYNAMICS_TIMEOUT,
            ParameterDescriptor(
                description=(
                    'How long (s) without a /hybraut_nav/continous_dynamics message '
                    'before the tactical layer is considered inactive and the control '
                    'loop commands an explicit stop instead of real motion. Generous '
                    "relative to tactical_node's own publish cadence (default 50 Hz) "
                    'so ordinary scheduling jitter never trips it. '
                    f'(default: {DEFAULT_CONTINUOUS_DYNAMICS_TIMEOUT})'
                ),
                type=ParameterType.PARAMETER_DOUBLE
            )
        )

    def __init_subscriptions__(self):
        self.odom_sub = self.create_subscription(
            msg_type=Odometry, 
            topic='/odom',
            callback=lambda msg: self.odom_cb(msg),
            qos_profile=qos_profile_system_default,
            callback_group=ReentrantCallbackGroup()
        )
        self.continous_dynamics_sub = self.create_subscription(
            msg_type=Float64MultiArray,
            topic='/hybraut_nav/continous_dynamics',
            callback=lambda msg: self.continous_dynamics_cb(msg),
            qos_profile=world_state_qos, # need to decide on a qos for continous dynamics for tactical layer
            callback_group=ReentrantCallbackGroup()
        )
        
    def __init_publishers__(self):
        self.cmd_vel_pub = self.create_publisher(
            Twist,  # msg_type
            '/cmd_vel',   # This is the output topic for turtlebot3's differential drive for giving target linear velocity and yaw rate
            qos_profile=QoSProfile(
                history=HistoryPolicy.KEEP_LAST,
                depth=10,
                reliability=ReliabilityPolicy.RELIABLE,
                durability=DurabilityPolicy.VOLATILE
            ),
            callback_group=ReentrantCallbackGroup()
        )
    
    def __init_timers__(self):
        self.control_timer = self.create_timer(
            timer_period_sec=1 / self.get_controller_frequency(),
            callback=self.control_loop,
            callback_group=ReentrantCallbackGroup()
        )

    def __init_controller__(self):
        self.ctrl: Controller = ControllerType.initialize_controller(
            self.get_controller_type()
        )


    """ === getters === """

    def get_controller_frequency(self) -> float:
        return self.get_parameter('controller_frequency').value

    def get_controller_type(self) -> str:
        return self.get_parameter('controller_type').value

    def get_desired_velocity(self) -> float:
        return self.get_parameter('desired_velocity').value

    def get_continuous_dynamics_timeout(self) -> float:
        return self.get_parameter('continuous_dynamics_timeout').value

    """ === setters === """
    def set_controller_frequency(self, new_frequency: float):
        ...

    """ === callbacks === """
    def control_loop(self):
        """Main control loop - always runs. Only ever commands real motion
        while /hybraut_nav/continous_dynamics is actively being published to
        (see _is_tactical_active()); otherwise commands an explicit stop, so
        the robot doesn't keep coasting on its last command once the
        tactical layer goes idle (leg reached/canceled/failed, or
        tactical_node isn't up)."""
        tactical_active = self._is_tactical_active()

        if tactical_active and not self._was_tactical_active:
            self.get_logger().info("tactical layer active - resuming control output")
            self.ctrl.reset()  # clear stale integral/derivative history from before the gap
        elif not tactical_active and self._was_tactical_active:
            self.get_logger().info("tactical layer inactive - holding station")
        self._was_tactical_active = tactical_active

        if not tactical_active:
            self._publish_cmd_vel(yaw_rate=0.0, linear_velocity=0.0)
            return

        try:
            commanded_yaw_rate = self.ctrl.step()
        except Exception as e:
            self.get_logger().error(f"Controller step failed: {e}")
            return

        self._publish_cmd_vel(commanded_yaw_rate, self.get_desired_velocity())

    def _is_tactical_active(self) -> bool:
        """True iff a /hybraut_nav/continous_dynamics message has arrived
        within continuous_dynamics_timeout - i.e. tactical_node currently
        has a leg running (its own publish timer only publishes that topic
        while one is)."""
        if self._last_continous_dynamics_time is None:
            return False
        elapsed = self.get_clock().now() - self._last_continous_dynamics_time
        return elapsed < Duration(seconds=self.get_continuous_dynamics_timeout())

    def continous_dynamics_cb(self, msg: Float64MultiArray):
        """Handle updates from tactical layer - refreshes the controller's
        setpoint and the liveness timestamp _is_tactical_active() checks.
        Publishing is handled by the control_loop timer."""
        if not isinstance(msg, Float64MultiArray):
            raise TypeError("Expected ContinousDynamics message.")

        self._last_continous_dynamics_time = self.get_clock().now()

        desired_heading = msg.data[2]  # rad, from tactical layer

        self.desired_heading = desired_heading
        self.ctrl.update_continous_dynamics(desired_heading)

    def _publish_cmd_vel(self, yaw_rate: float, linear_velocity: float):
        self.desired_yaw_rate = yaw_rate

        twist = Twist()
        # twist.header.stamp = self.get_clock().now().to_msg()
        # twist.header.frame_id = 'odom'
        # twist.twist.angular.z = yaw_rate
        # twist.twist.linear.x = linear_velocity

        twist.angular.z = yaw_rate
        twist.linear.x = linear_velocity

        self.cmd_vel_pub.publish(twist)

    def odom_cb(self, msg: Odometry):
        """Update the controller's current heading from odometry."""
        orientation = msg.pose.pose.orientation
        current_heading = quaternion_to_heading(
            orientation.x, orientation.y, orientation.z, orientation.w
        )
        self.ctrl.update_state(current_heading)

    def base_link_cb(self, msg: Twist):
        self.base_link_state = msg


def main(args=None):
    from rclpy.executors import MultiThreadedExecutor

    rclpy.init(args=args)
    node = ImmediateNode()
    executor = MultiThreadedExecutor(num_threads=os.cpu_count())
    executor.add_node(node)

    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()