# controller_node.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python3
"""
Implementation of the Guidance and Control Layer (Layer 3) of the HybrautNav 
Navigation Stack.

This layer integrates the finite-time high-level guidance controller and 
produces reference commands—desired yaw rate and desired velocity—that will 
be tracked by downstream low-level controllers (e.g., PID, differential-drive, 
MPC). It acts as the closure of the HybrautNav stack for fast control loops, 
bridging the tactical continuous dynamics and the physical control execution.

Responsibilities:
- Integrates the high-level guidance controller into real-time control loops
- Enforces safety limits and parameter constraints
- Provides hardware interfacing pathways (rudder, thrusters, actuators)
- Allows the L2 Tactical Layer to remain physics-agnostic by handling 
  vessel-specific control considerations here

NOTE:
This version of the controller assumes a constant forward velocity and relies 
on the continuous dynamics from the hybraut_tactical_layer to supply only a 
desired heading. Future versions may support richer dynamic references.
"""

import math
from typing import Optional

from rclpy.callback_groups import ReentrantCallbackGroup
import os

import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_system_default
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.subscription import Subscription
from rclpy.publisher import Publisher
from rclpy.service import Service
from rcl_interfaces.msg import ParameterDescriptor

from geometry_msgs.msg import TwistStamped, TransformStamped
from nav_msgs.msg import Odometry
from std_srvs.srv import Trigger

from hybraut_nav.qos import world_state_qos

from std_msgs.msg import Float64MultiArray

from hybraut_nav.state import NodeState
from hybraut_nav_utils import quaternion_to_heading

from .controller import ControllerType, Controller

from rcl_interfaces.msg import ParameterType

DEFAULT_CONTROLLER_FREQUENCY: float = 100.0  # Hz
DEFAULT_CRUISE_SPEED: float = 0.2 # m/s       
DEFAULT_YAW_RATE_LIMIT: float = 0.2
DEFAULT_DESIRED_HEADING: float = 0.0

import numpy as np


class ImmediateNode(Node):
    """
    ImmediateNode is a core component of the HybrautNav Navigation Stack,
    integrating a heading-guidance controller into the
    Planning–Behaviour–Guidance architecture.

    This node computes high-level guidance commands—specifically desired
    yaw rate and desired velocity—based on the continuous dynamics provided
    by the L2 Tactical Layer’s Hybrid Automaton and the current state of the
    agent vehicle. In this version, the controller assumes a constant forward
    velocity and uses the desired heading from the tactical layer as its
    primary reference.

    The underlying controller is pluggable via the `controller_type` ROS
    parameter (see `ControllerType`) - defaults to a PID controller for
    now, since the intended finite-time guidance controller
    (`finite_time_control`) isn't published/ready yet. It produces
    reference commands that downstream low-level controllers can track,
    incorporating the vessel’s physical parameters as needed.

    This node also manages dynamic reconfiguration of controller parameters
    and supports runtime switching of control modes—whether triggered manually
    by a human operator or automatically via updates from continuous-dynamics
    messages generated by the tactical layer.
    """

    # internal state
    state: NodeState = NodeState.INACTIVE
    ctrl: Optional[Controller] = None

    desired_heading: float = 0.0

    desired_velocity: float = 10.0
    desired_yaw_rate: float = 0.0

    # State variables
    agent_state: Optional[Odometry] = None
    
    # Subscriptions
    odom_sub: Subscription = None
    # Publishers
    cmd_vel_pub: Publisher = None
    
    # services 
    toggle_controller_srv: Service = None

    
    def __init__(self):
        super().__init__('controller_node', namespace='hybraut_nav')
        
        self.__init_parameters__()
        self.__init_subscriptions__()
        self.__init_publishers__()
        self.__init_timers__()
        self.__init_services__()
        self.__init_controller__()

    def __init_parameters__(self):
        self.declare_parameter(
            'controller_frequency',
            DEFAULT_CONTROLLER_FREQUENCY,
            ParameterDescriptor(
                description='Frequency (Hz) at which to run the controller loop. '
                            f'(default: {DEFAULT_CONTROLLER_FREQUENCY} Hz)',
                type=ParameterType.PARAMETER_DOUBLE
            )
        )
        self.declare_parameter(
            'controller_type',
            ControllerType.PID_CONTROLLER.value,
            ParameterDescriptor(
                description='Which guidance controller to run - see ControllerType '
                            f'(default: "{ControllerType.PID_CONTROLLER.value}")',
                type=ParameterType.PARAMETER_STRING
            )
        )
        self.declare_parameter(
            'desired_velocity',
            DEFAULT_CRUISE_SPEED,
            ParameterDescriptor(
                description='Velocity (m/s) in which the controller will' \
                    f'operate a cruise speed, this version of hybraut_nav_controller' \
                    f'outputs a constant cruise speed for `cmd_vel` based on this' \
                    f'(default: {DEFAULT_CRUISE_SPEED})',
                type=ParameterType.PARAMETER_DOUBLE
            ),
        )
        self.declare_parameter(
            'desired_heading',
            DEFAULT_DESIRED_HEADING,
            ParameterDescriptor(
                description='Desired heading for the guidance controller currently',
                type=ParameterType.PARAMETER_DOUBLE
            )
        )
        self.declare_parameter(
            'yaw_rate_limit',
            DEFAULT_YAW_RATE_LIMIT,
            ParameterDescriptor(
                description=(
                    'Yaw rate limit defines the constraints of yaw rate for the '
                    f'guidance controller (default: {DEFAULT_YAW_RATE_LIMIT})'
                ),
                type=ParameterType.PARAMETER_DOUBLE
            )
        )

    def __init_subscriptions__(self): 
        self.odom_sub = self.create_subscription(
            msg_type=Odometry, 
            topic='/odom',
            callback=lambda msg: self.odom_cb(msg),
            qos_profile=qos_profile_system_default,
            callback_group=ReentrantCallbackGroup()
        )
        # self.base_link_sub=self.create_subscription(
        #     msg_type=TransformStamped,
        #     topic='/base_link',
        #     callback=lambda msg: self.base_link_cb(msg), 
        #     qos_profile=None,
        #     callback_group=ReentrantCallbackGroup()
        # )

        # TODO: continous_x state needs to be below
        # tf2_ros.Buffer().lookup_transform("odom", "base_link") # APPLYS ROTATION THEN TRANSLATION


        self.continous_dynamics_sub = self.create_subscription(
            msg_type=Float64MultiArray,
            topic='/hybraut_nav/continous_dynamics',
            callback=lambda msg: self.continous_dynamics_cb(msg),
            qos_profile=world_state_qos, # need to decide on a qos for continous dynamics for tactical layer
            callback_group=ReentrantCallbackGroup()
        )
        
    def __init_publishers__(self):
        self.cmd_vel_pub = self.create_publisher(
            TwistStamped,  # msg_type
            '/cmd_vel',   # This is the output topic for turtlebot3's differential drive for giving target linear velocity and yaw rate
            qos_profile_system_default,
            callback_group=ReentrantCallbackGroup()
        )
    
    def __init_services__(self):
        """ initializes services"""
        self.toggle_controller_srv = self.create_service(
            Trigger,
            'controller_node/toggle',
            self.toggle_controller_cb,
            callback_group=ReentrantCallbackGroup()
        )

    def __init_timers__(self):
        self.control_timer = self.create_timer(
            timer_period_sec=1 / self.get_controller_frequency(),  # 10 Hz control loop
            callback=self.control_loop,
            callback_group=ReentrantCallbackGroup(),
            autostart=False
        ) 

    def __init_controller__(self):
        self.ctrl: Controller = ControllerType.initialize_controller(
            self.get_controller_type()
        )


    """ === getters === """

    def get_controller_frequency(self) -> float:
        return self.get_parameter('controller_frequency').value

    def get_controller_type(self) -> str:
        return self.get_parameter('controller_type').value

    def get_desired_velocity(self) -> float:
        return self.get_parameter('desired_velocity').value

    def get_desired_heading(self) -> float:
        return self.get_parameter('desired_heading').value

    """ === setters === """
    def set_controller_frequency(self, new_frequency: float):
        ...

    """ === callbacks === """
    def control_loop(self):
        """Main control loop to compute and publish actuator commands."""
        if self.state == NodeState.ACTIVE:
            try:
                commanded_yaw_rate = self.ctrl.step()
            except Exception as e:
                self.get_logger().error(f"Controller step failed: {e}")
                return

            self._publish_cmd_vel(commanded_yaw_rate)

    def continous_dynamics_cb(self, msg: Float64MultiArray):
        """Handle updates from tactical layer - refreshes the controller's
        setpoint. Publishing is handled by the control_loop timer."""
        if not isinstance(msg, Float64MultiArray):
            raise TypeError("Expected ContinousDynamics message.")

        desired_heading = msg.data[2]  # rad, from tactical layer

        self.desired_heading = desired_heading
        self.ctrl.update_continous_dynamics(desired_heading)

    def _publish_cmd_vel(self, commanded_yaw_rate: float):
        self.desired_yaw_rate = commanded_yaw_rate

        twist = TwistStamped()
        twist.header.stamp = self.get_clock().now().to_msg()
        twist.header.frame_id = '/map'
        twist.twist.angular.z = commanded_yaw_rate
        twist.twist.linear.x = self.get_desired_velocity()

        self.cmd_vel_pub.publish(twist)

    def odom_cb(self, msg: Odometry):
        """Update the controller's current heading from odometry."""
        orientation = msg.pose.pose.orientation
        current_heading = quaternion_to_heading(
            orientation.x, orientation.y, orientation.z, orientation.w
        )
        self.ctrl.update_state(current_heading)

    def base_link_cb(self, msg: TwistStamped):
        self.base_link_state = msg
        
    def toggle_controller_cb(self, request: Trigger.Request, response: Trigger.Response):
        # Toggle controller state
        if self.state == NodeState.ACTIVE:
            self.state = NodeState.INACTIVE
            response.success = True
            response.message = "Controller deactivated."
            self.control_timer.cancel()
        else:
            self.state = NodeState.ACTIVE
            response.success = True
            response.message = "Controller activated."
            self.control_timer.reset()
            
        return response
    

def main(args=None):
    from rclpy.executors import MultiThreadedExecutor

    rclpy.init(args=args)
    node = ImmediateNode()
    executor = MultiThreadedExecutor(num_threads=os.cpu_count())
    executor.add_node(node)

    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()