<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hybraut_nav</name>
  <version>1.0.0</version>
  <description>hybraut_nav is a ros2-rclpy navigation stack based on enabling hybrid automaton tactical layer for informed control.</description>
  <maintainer email="ryanmckee47@icloud.com">Ryan McKee</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>rcl_interfaces</depend>
  <depend>builtin_interfaces</depend>
  <depend>message_filters</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>colav_interfaces</depend>
  <depend>hybraut_interfaces</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>autoware_testing</test_depend>
  <test_depend>parameterized</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
