# ===================================================
# ROS Hybrid Automaton Framework ( internal topics )
# ===================================================
#
# This file formalises the internal communication topics between the Hybrid 
# Automaton Nodes
# Each node has their topic name as well as there ros2 message type.

# TODO: Need to finish this

hybrid_automaton:
  mode: 
    topic: "/hybrid_automaton/mode"
    msg_type: "std_msgs/String"
  transitions: 
    topic: "/"
    msg_type: "hybrid_automaton_interfaces/msg/Transition"
  transition_pending: 
  transition_timer: 
  dynamics: 


  state:
    waypoints: 