@startuml CancelGoalCallbackFlowChart
    start

        :Cancel Goal Callback;

        if (state == active?) then (yes)
            :Cancel replan timer;
            :Toggle state to inactive;
            :Reset goal-related attributes: goal_pose, virtual_waypoint;
            :Return success message:IO;
        else (no)
            :Return failed message: state already inactive:IO;
        endif

    stop
@enduml
