@startuml StrategyNodeStateMachine
[*] --> INACTIVE

INACTIVE --> ACTIVE : on_goal_callback

state ACTIVE {
    [*] --> RUNNING

    RUNNING --> RUNNING : not goalReached
    RUNNING --> INACTIVE : goalReached
    RUNNING --> INACTIVE : on_cancel_goal
}

@enduml
