@startuml StrategyNodeClassDiagram

class PlannerType <<Enum>> {
    ASTAR = 'AStar'
    DIJKSTRA = 'Dijkstra'
    RRT = 'RRT'
    RRTSTAR = 'RRT*'
    
    --Methods--
    + <<staticmethod>> from_string(planner_type_str: str): 'PlannerType'
}

class StrategyState <<Enum>> {
    INACTIVE = "inactive"
    ACTIVE = "active"
}

class StrategyNode <<Node>> {
    # ROS2 Parameter Defaults
    - {static} DEFAULT_REPLAN_FREQUENCY: double = 0.1
    - {static} DEFAULT_MAX_PLANNING_TIME: double = 5.0
    - {static} DEFAULT_PLANNER_TYPE: str: String = PlannerType.ASTRA.value
    
    # World State Class Attributes
    - map: PlannerGrid = None
    - start_point: PlannerPoint = None
    - goal_point: PlannerPoint = None
    - vw_point: PlannerPoint = None
    
    # Node State Variables
    - state: StrategyState = StrategyState.INACTIVE
    - planner: Planner = None
    
    # ROS2 publisher
    - plan_pub: Publisher = None
    - goal_point_pub: Publisher = None
    
    # ROS2 subscriptions
    - map_sub: Subscription = None
    - agent_sub: Subscription = None
    - vw_sub: Subscription = None
    
    # ROS2 services
    - send_goal_srv: Service = None
    - cancel_goal_srv: Service = None
    
    
    # Timers
    - replan_timer: Timer = None
    
    -- Methods --
    # initialization
    __init__()
    __init_parameters__()
    __init_services__()
    __init_subscriptions__()
    __init_publishers__()
    __init_timer__()
    
    # getters
    + get_replan_frequency(): double
    + get_planner_type(): String
    + get_max_planning_time(): double
    + get_description(): String
    + get_state(): StrategyState
    
    # setters
    + set_planner(planner_type: Union[PlannerType, String], reset_replan_timer: bool = False)
    + set_max_planning_time(new_max_planning_time: double, reset_replan_timer: bool = False)
    + set_replan_frequency(new_replan_frequency: double, reset_replan_timer: bool = False)
    
    # Service Callback functions
    - goal_received_callback(request: SendPose.Request, response: SendPose.Response)
    - cancel_goal_callback(request: Trigger.Request, response: Trigger.Response)
    
    # Topic callbacks
    - map_callback(msg: OccupancyGrid)
    - agent_callback(msg: AgentState)
    - vw_callback(msg: Point) 
    
    # Timer callback
    - replan_callback()
    
    # Parameter callback
    - parameter_callback(params: List[Parameter]) -> SetParameterResult
    
    # Helper Functions
    - is_active(): bool
    - toggle_state()
    - publish_plan(path: Path)

}
@enduml
