stateDiagram-v2
# colav famd FAMD State Diagram
    %% Initial Mode
    [*] --> cruise: initial_mode
    %% Modes
    cruise: 0.cruise

    note left of cruise
      invariant: trivial_invariant
      dynamics: proportional_velocity_controller
    end note
    t2los: 1.t2los

    note left of t2los
      invariant: trivial_invariant
      dynamics: proportional_yaw_rate_controller
    end note
    waypoint_reached: 2.waypoint_reached

    note left of waypoint_reached
      invariant: is_at_final_waypoint
      dynamics: no_op_controller
    end note
    fallback: 3.fallback

    note left of fallback
      invariant: failing_invariant
      dynamics: no_op_controller
    end note
    %% Transitions
    cruise --> t2los: 2.plan_evasive_maneuver
    cruise --> t2los: 3.correct_heading
    cruise --> fallback: 0.enter_emergency_fallback
    t2los --> fallback: 0.enter_emergency_fallback
    cruise --> waypoint_reached: 1.waypoint_arrival
    t2los --> waypoint_reached: 2.waypoint_arrival
    t2los --> cruise: 0.heading_aligned
    waypoint_reached --> cruise: 0.proceed_to_next_waypoint
    # Goal Modes
    waypoint_reached --> [*]: goal_reached
    # Transitions
