
# Goal
builtin_interfaces/Time stamp         # Timestamp for synchronization
unique_identifier_msgs/UUID mission_uuid  # Unique identifier for the mission
string mission_profile  # Define the type of mission (e.g., "fastest_path", "safe_navigation")
unique_identifier_msgs/UUID agent_uuid   # Unique identifier for the agent (e.g., vessel, drone)
hybrid_automaton_interfaces/Waypoint goal_waypoint  # Target waypoint for the agent to reach

---
# Result
bool success
string message

---

# Response
hybrid_automaton_interfaces/Output feedback