
# Goal
builtin_interfaces/Time stamp         # Timestamp for synchronization
string mission_tag                      # tag for the mission.
colav_interfaces/Waypoint[] goal_waypoints  # Target waypoint for the agent to reach

---
# Result
bool success
string message

---

# Response
hybrid_automaton_interfaces/Output feedback