stateDiagram-v2
    direction LR

    %% Entry point
    [*] --> 0.INIT: 0.SYSTEM_BOOT

    %% INIT to IDLE
    0.INIT --> 1.IDLE: 2.INIT_COMPLETED

    %% IDLE to ACTIVE
    1.IDLE --> 2.ACTIVE: 3.MISSION_RECEIVED

    %% ACTIVE transitions
    %% SHOULD BE A TRANSITION_FAILURE, TRANSITION FAILURE IS ALWAYS GOING TO CAUSE AN ERROR, WHEN THIS HAPPENS OUR FSM CAN RETRY THE PREVIOUS TRANSITION
    %% BY MAKING A REQUEST ONE MORE TIME, IF IT FAILS AGAIN IT IS FATAL 
    2.ACTIVE --> 3.TRANSITIONING: 5.TRANSITION_GUARD_ENABLED
    3.TRANSITIONING --> 2.ACTIVE: 6.TRANSITION_COMPLETE
    3.TRANSITIONING --> 5.ERROR: 14.TRANSITION_FAILURE

    2.ACTIVE --> 4.WARNING: 7.NON_BLOCK_ANOMALY 
    4.WARNING --> 2.ACTIVE: 8.ANOMALY_RESOLVED_OR_TIMEOUT 

    2.ACTIVE --> 5.ERROR: 9.RECOVERABLE_ERROR
    5.ERROR --> 6.RECOVERING: 11.ATTEMPT_FIX
    6.RECOVERING --> 2.ACTIVE: 13.RECOVERED
    5.ERROR --> 7.FATAL: 12.CRITICAL_FAILURE

    %% FATAL terminal
    7.FATAL --> [*]

    %% Goal complete
    2.ACTIVE --> 8.MISSION_COMPLETE: 10.MISSION_COMLETE
    8.MISSION_COMPLETE --> [*]

    %% Other entries
    1.IDLE --> 7.FATAL: 4.INIT_MISSION_FAILURE
    0.INIT --> 7.FATAL: 1.BOOT_FAILURE