%% StrategyNode::set_replan_frequency
%% Type: flowchart
%% Version: 0.0.2

flowchart TD
    Start([Start]) --> CheckValid{{Is new_replan_frequency valid?}}
    CheckValid -- No --> RaiseException["Raise Exception"]
    CheckValid -- Yes --> UpdateParam[/"Update ROS2 Parameter: replan_frequency = new_replan_frequency"/]
    UpdateParam --> CheckTimer{{Is replan_timer active?}}
    CheckTimer -- Yes --> RecreateTimerAuto[/"Recreate replan_timer (autostart = True)"/]
    CheckTimer -- No --> RecreateTimerManual[/"Recreate replan_timer (autostart = False)"/]
    RaiseException --> End([End])
    RecreateTimerAuto --> End
    RecreateTimerManual --> End
