stateDiagram-v2
    %% colav_hybrid_automaton State Diagram

    %% Initial Mode
    [*] --> 0

    %% Modes
    0 : 0.cruise
    note left of 0
        =====================
        <b>0.cruise</b>
        =====================
        <b>description</b>: Cruise mode with pid controller tuned for cruise mode.
        <b>invariant</b>: trivial_invariant
        <b>dynamics</b>: cruise_pid_controller
    end note

    1 : 1.t2los
    note left of 1
        =====================
        <b>1.t2los</b>
        =====================
        <b>description</b>: Transition to Line of Sight (T2LOS) mode with proportional yaw rate control
        <b>invariant</b>: trivial_invariant
        <b>dynamics</b>: t2los_pid_controller
    end note

    2 : 2.waypoint_reached
    note left of 2
        =====================
        <b>2.waypoint_reached</b>
        =====================
        <b>description</b>: Waypoint reached mode, indicating successful navigation to a waypoint
        <b>invariant</b>: is_goal_waypoint_invariant
        <b>dynamics</b>: no_op_controller
    end note

    3 : 3.fallback
    note left of 3
        =====================
        <b>3.fallback</b>
        =====================
        <b>description</b>: Fallback mode for emergency conditions, no active control
        <b>invariant</b>: failing_invariant
        <b>dynamics</b>: no_op_controller
    end note

    %% Transitions
    0 --> 1 : <b>2.plan_evasive_maneuver</b>  [<b>guard</b> = los_clear_to_waypoint_guard, <b>reset</b> = generate_virtual_waypoint_reset]
    0 --> 1 : <b>3.correct_heading</b>  [<b>guard</b> = heading_not_within_tolerance_guard, <b>reset</b> = None]
    0 --> 3 : <b>0.enter_emergency_fallback</b>  [<b>guard</b> = unsafe_conditions_guard, <b>reset</b> = None]
    1 --> 3 : <b>0.enter_emergency_fallback</b>  [<b>guard</b> = unsafe_conditions_guard, <b>reset</b> = None]
    0 --> 2 : <b>1.waypoint_arrival</b>  [<b>guard</b> = waypoint_reached_guard, <b>reset</b> = None]
    1 --> 2 : <b>2.waypoint_arrival</b>  [<b>guard</b> = waypoint_reached_guard, <b>reset</b> = None]
    %% Goal Modes
    2 --> [*]
