stateDiagram-v2
    %% colav_hybrid_automaton State Diagram

    %% Initial Mode
    [*] --> 0

	%% Modes
	%% cruise Mode details
    0 : 0.cruise
    note left of 0
        =====================
        <b>0.cruise</b>
        =====================
        <b>description</b>: Cruise mode with pid controller tuned for cruise mode.
        <b>invariants</b>: ['TrivialInvariant, No description']
        <b>dynamics</b>: PIDControllerDynamics, PIDYawVelocityController
    end note

	%% cruise transitions.
    0 --> 3 : <b>0.enter_emergency_fallback</b>  [<b>guard</b> = UnsafeConditionsGuard, <b>reset</b> = Null]
    0 --> 2 : <b>1.waypoint_arrival</b>  [<b>guard</b> = WaypointReachedGuard, <b>reset</b> = Null]
    0 --> 1 : <b>2.plan_evasive_maneuver</b>  [<b>guard</b> = LOSClearToWaypointGuard, <b>reset</b> = GenerateVirtualWaypointReset]
    0 --> 1 : <b>3.correct_heading</b>  [<b>guard</b> = HeadingNotWithinToleranceGuard, <b>reset</b> = Null]

	%% t2los Mode details
    1 : 1.t2los
    note left of 1
        =====================
        <b>1.t2los</b>
        =====================
        <b>description</b>: Transition to Line of Sight (T2LOS) mode with proportional yaw rate control
        <b>invariants</b>: ['TrivialInvariant, No description']
        <b>dynamics</b>: PIDControllerDynamics, PIDYawVelocityController
    end note

	%% t2los transitions.
    1 --> 3 : <b>0.enter_emergency_fallback</b>  [<b>guard</b> = UnsafeConditionsGuard, <b>reset</b> = Null]
    1 --> 0 : <b>1.heading_aligned</b>  [<b>guard</b> = HeadingWithinToleranceGuard, <b>reset</b> = Null]
    1 --> 2 : <b>2.waypoint_arrival</b>  [<b>guard</b> = WaypointReachedGuard, <b>reset</b> = Null]

	%% waypoint_reached Mode details
    2 : 2.waypoint_reached
    note left of 2
        =====================
        <b>2.waypoint_reached</b>
        =====================
        <b>description</b>: Waypoint reached mode, indicating successful navigation to a waypoint
        <b>invariants</b>: ['IsGoalWaypointInvariant, No description']
        <b>dynamics</b>: NoOpControllerDynamics, No description
    end note

	%% waypoint_reached transitions.
    2 --> 0 : <b>0.proceed_to_next_waypoint</b>  [<b>guard</b> = VirtualWaypointsGuard, <b>reset</b> = RemoveVirtualWaypointReset]

	%% fallback Mode details
    3 : 3.fallback
    note left of 3
        =====================
        <b>3.fallback</b>
        =====================
        <b>description</b>: Fallback mode for emergency conditions, no active control
        <b>invariants</b>: ['FailingInvariant, No description']
        <b>dynamics</b>: NoOpControllerDynamics, No description
    end note

	%% fallback transitions.

    %% Goal Modes
    2 --> [*]
